#
# AdvanceParticle plugin config file
# "true" - Enable use particle
# "false" - Disable use particle
PARTICLES:
  EXPLOSION_NORMAL: true
  EXPLOSION_LARGE: true
  EXPLOSION_HUGE: true
  FIREWORK_SPARK: true
  WATER_SPLASH: true
  WATER_WAKE: true
  DEPTH_SUSPEND: true
  CRIT: true
  CRIT_MAGIC: true
  SMOKE_NORMAL: true
  SMOKE_LARGE: true
  SPELL: true
  SPELL_INSTANT: true
  SPELL_MOB: true
  SPELL_MOB_AMBIENT: true
  SPELL_WITCH: true
  DRIP_WATER: true
  DRIP_LAVA: true
  VILLAGER_ANGRY: true
  VILLAGER_HAPPY: true
  TOW_AURA: true
  NOTE: true
  PORTAL: true
  ENCHANT_TABLE: true
  FLAME: true
  LAVA: true
  FOOTSTEP: true
  CLOUD: true
  REDSTONE: true
  SNOWBALL: true
  SNOW_SHOVEL: true
  SLIME: true
  HEART: true
  WATER_DROP: true
  DRAGON_BREATH: true
  END_ROD: true
  DAMAGE_INDICATOR: true
  SWEEP_ATTACK: true
#
# MySQL features
# If is MySQL enable plugin save player and particles data to MySQL, local database system is disable
MySQL:
  enable: false
  host: localhost
  port: 3306
  database: localhost
  username: root
  password: ''
  table: ap_